"""add_owner_id_to_teams

Revision ID: b2b8fdbb8706
Revises: e92afeeafbe5
Create Date: 2025-12-12 11:50:37.882263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b8fdbb8706'
down_revision: Union[str, Sequence[str], None] = 'e92afeeafbe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'owner_id')
    # ### end Alembic commands ###
